---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
plugins:
  - solargraph-standardrb
reporters:
  - standardrb
require_paths: []
max_files: 5000
