# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mail_style}
  s.version = "1.0.0.pre1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Neath"]
  s.date = %q{2010-11-08}
  s.description = %q{Making HTML emails a little less painful. Writes css inline and corrects image urls.}
  s.email = %q{jimneath@googlemail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
    "Rakefile",
    "lib/mail_style.rb",
    "lib/mail_style/action_mailer_extensions.rb",
    "lib/mail_style/inliner.rb",
    "spec/fixtures/public/stylesheets/bar.css",
    "spec/fixtures/public/stylesheets/foo.css",
    "spec/fixtures/public/stylesheets/integration.css",
    "spec/fixtures/views/integration_mailer/notification.html.erb",
    "spec/fixtures/views/integration_mailer/notification.text.erb",
    "spec/integration_spec.rb",
    "spec/lib/mail_style/action_mailer_extensions_spec.rb",
    "spec/lib/mail_style/inliner_spec.rb",
    "spec/lib/mail_style_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/purify/mail_style}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Making HTML emails a little less painful}
  s.test_files = [
    "spec/integration_spec.rb",
    "spec/lib/mail_style/action_mailer_extensions_spec.rb",
    "spec/lib/mail_style/inliner_spec.rb",
    "spec/lib/mail_style_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<css_parser>, [">= 0"])
      s.add_runtime_dependency(%q<actionmailer>, ["~> 3.0.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.0.pre5"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.0.0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<css_parser>, [">= 0"])
      s.add_dependency(%q<actionmailer>, ["~> 3.0.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre5"])
      s.add_dependency(%q<rspec-rails>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<css_parser>, [">= 0"])
    s.add_dependency(%q<actionmailer>, ["~> 3.0.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre5"])
    s.add_dependency(%q<rspec-rails>, [">= 2.0.0"])
  end
end

